version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # nuxt:
  #   image: node:latest
  #   container_name: nuxt_app
  #   restart: always
  #   working_dir: /app
  #   volumes:
  #     - ./nuxt-app:/app
  #   command: npm run start
  #   ports:
  #     - "3000:3000"
  #
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - nuxt

volumes:
  mongodb_data:
